EpamLab/JSFNewsmanagementClient/src/main/java/com/epam/newsmanagement/bean/LanguageBean.java
package com.epam.newsmanagement.bean;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;

/**
 * Created by Sviatlana_Andryianch on 1/27/2016.
 */
@ManagedBean(name="language")
@SessionScoped
public class LanguageBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private String localeCode;

    private static Map<String,Object> countries;
    static{
        countries = new LinkedHashMap<String,Object>();
        countries.put("English", Locale.ENGLISH); //label, value
        countries.put("Russian", new Locale("RU"));
    }

    public Map<String, Object> getCountriesInMap() {
        return countries;
    }


    public String getLocaleCode() {
        return localeCode;
    }


    public void setLocaleCode(String localeCode) {
        this.localeCode = localeCode;
    }

    //value change event listener
    public void countryLocaleCodeChanged(ValueChangeEvent e){

        String newLocaleValue = e.getNewValue().toString();

        //loop country map to compare the locale code
        for (Map.Entry<String, Object> entry : countries.entrySet()) {

            if(entry.getValue().toString().equals(newLocaleValue)){

                FacesContext.getCurrentInstance()
                        .getViewRoot().setLocale((Locale)entry.getValue());

            }
        }
    }

}

EpamLab/JSFNewsmanagementClient/src/main/webapp/WEB-INF/views/templates/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:h="http://java.sun.com/jsf/html">
<h:body>
    <div class = "footer-content">
        Copyright @ Epam 2015. All rights reserved.
    </div>
</h:body>
</html>

EpamLab/JSFNewsmanagementClient/src/main/webapp/WEB-INF/views/templates/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:spring="http://www.springframework.org/tags"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core">
<h:head></h:head>
<h:body>

<div class="header-content">
    <h2>
        <h:outputText value="#{message['header.label']}" />
    </h2>
    <div class = "languages">
        <!--<a href="?lang=en"><spring:message code="header.language.en" /></a> |
        <a href="?lang=ru"><spring:message code="header.language.ru" /></a>-->

            <h:form>

                <h:panelGrid columns="2">

                    Language :
                    <h:selectOneMenu value="#{language.localeCode}" onchange="submit()"
                                     valueChangeListener="#{language.countryLocaleCodeChanged}">
                        <f:selectItems value="#{language.countriesInMap}" />
                    </h:selectOneMenu>

                </h:panelGrid>

            </h:form>



    </div>


</div>
</h:body>
</html>

EpamLab/JSFNewsmanagementClient/src/main/webapp/WEB-INF/views/templates/layout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

<h:head>
    <title>News Managment</title>
</h:head>
<h:body>

<h:outputStylesheet library="css" name="layout.css"  />
<div class="main">
    <div class="header">
        <ui:insert name="header">
            <ui:include src="/WEB-INF/views/templates/header.xhtml" />
        </ui:insert>
    </div>

    <div class="body">
        <div class="content">
            <div class="menu">
                <div class = "menu-content">
                    <ui:insert name="menu">
                        <ui:include src="/WEB-INF/views/templates/menu.xhtml" />
                    </ui:insert>
                </div>
            </div>
            <div class="inner-data">
                <ui:insert name="body" />
            </div>
        </div>
    </div>
    <div class="footer">
        <ui:insert name="footer">
            <ui:include src="/WEB-INF/views/templates/footer.xhtml" />
        </ui:insert>
    </div>
</div>
</h:body>

</html>

EpamLab/JSFNewsmanagementClient/src/main/webapp/WEB-INF/views/templates/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
<h:head></h:head>
<h:body>
<p><h:graphicImage value="resources/images/arrow.png"/>  <a href="/news-admin/newsList"><h:outputText value="#{message['menu.list']}"/></a></p>
<p><h:graphicImage value="resources/images/arrow.png"/>  <a href="/news-admin/addNews"><h:outputText value="#{message['menu.addnews']}"/></a></p>
<p><h:graphicImage value="resources/images/arrow.png"/>  <a href="/news-admin/authors"><h:outputText value="#{message['menu.authors']}"/></a></p>
<p><h:graphicImage value="resources/images/arrow.png"/>  <a href="/news-admin/tags"><h:outputText value="#{message['menu.tags']}"/></a></p>
</h:body>
</html>